export const SALVA_CATEGORIAS = "SALVA_CATEGORIAS";
export const SALVA_PRODUTO_POR_CATEGORIA_POR_ID =
  "SALVA_PRODUTO_POR_CATEGORIA_POR_ID";
export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const SALVA_FRETE = "SALVA_FRETE";
