import { makeStyles } from "@material-ui/core/styles";
import colors from "../../util/Colors";

const useStyles = makeStyles((theme) => ({
  button: {
    WebkitAppearance: "none",
    appearance: "none",
    WebkitFilter: "drop-shadow(0 5px 5px rgba(0, 0, 0, 0.1))",
    filter: "drop-shadow(0 5px 5px rgba(0, 0, 0, 0.1))",
    WebkitTransition: "all .5s ease",
    transition: "all .5s ease",
    border: "none",
    color: colors.white,
    background: colors.orangeDarkDark,
    borderRadius: "30px",
    textTransform: "capital",
    boxSizing: "border-box",
    padding: "15px 40px",
    fontWeight: "400",
    width: "200px",
    fontSize: "13px",
    cursor: "pointer",
    float: "left",
    "&:hover": {
      color: "#FFFFFF",
      background: "#222222",
      WebkitFilter: "drop-shadow(0 0 5px rgba(0, 0, 0, 0.2))",
      filter: "drop-shadow(0 0 5px rgba(0, 0, 0, 0.2))",
    },
  },
  link: {
    background: colors.white,
    display: "flex",
    height: "100%",
  },
  h1: {
    fontWeight: "600",
    maxWidth: "840px",
    color: colors.orangeDark,
    fontSize: "45px",
    lineHeight: "1",
    transition: "all 0.3s ease",
    WebkitTransform: "translateY(-20px)",
    transform: "translateY(-20px)",
    textAlign: "left",
  },
  p: {
    color: colors.orangeDark,
    fontSize: "35px",
    fontWeight: "400",
    lineHeight: "1.5",
    marginBottom: "50px",
    maxWidth: "640px",
    transition: "all 0.3s ease",
    WebkitTransform: "translateY(20px)",
    transform: "translateY(20px)",
    textAlign: "left",
  },
  div: {
    width: "70%",
    display: "flex",
    flexWrap: "wrap",
    top: "0%",
    alignContent: "center",
    zIndex: "0",
    height: "100%",
    marginLeft: "10%",
  },
  imagemDiv: {
    float: "right",
    width: "500px",
    zIndex: "1",
    marginRight: "26%",
    height: "100%",
    position: "relative",
  },
  imagem: {
    position: "absolute",
    margin: "auto",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    height: "300px",
  },
  sliderContent: {
    textAlign: "center",
    width: "100%",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    inner: {
      padding: "0 70px",
      boxSizing: "border-box",
      position: "absolute",
      width: "100%",
      top: "50%",
      left: "50%",
      WebkitTransform: "translate(-50%, -50%)",
      transform: "translate(-50%, -50%)",
    },
  },
  previousButton: {
    left: "0",
    WebkitTransform: "rotate(180deg) translateY(calc(50% + 0px))",
    transform: "rotate(180deg) translateY(calc(50% + 0px))",
    "&:hover": {
      left: "-10px",
    },
  },
  nextButton: {
    right: "0",
    "&:hover": {
      right: "-10px",
    },
  },
}));

export default useStyles;
